### ISSUE TITLE
I've pasted the contents to "data" and my game no longer loads

### ISSUE THREAD

**Issue by Jan-Blasiak** [Zenefess/wide-sidebar-cdda#1]
DEBUG    : Error: Json error: data/json/ui/zenfs/environment.json:103:21: <color_white><color_cyan>unrecognized number source in moon</color>

        "text": "New moon  ",
        "color": "white",
<color_light_red>        "condition": { "compare_num": [ "moon", "==", { "const": 0 } ] }</color>
                   <color_cyan>▲▲▲</color>
      },
      {
</color>

 FUNCTION : bool main_menu::load_game(const std::string&, const save_t&)
 FILE     : src/main_menu.cpp
 LINE     : 1038
 VERSION  : cdc3058

**Comment by Jan-Blasiak** [comment]
![obraz](https://github.com/Zenefess/wide-sidebar-cdda/assets/61629226/36bdc2e0-2fe4-463f-8da2-1794dcd0de24)

**Comment by Zenefess** [comment]
My apologies for the delay. The 'compare_num' function is being replaced and removed. Thanks for letting me know it's already happening. The version that is included in the official build has been rewritten, but the versions available here are for earlier releases. I will upload the latest official build version as soon as I've finished dinner.

**Comment by Zenefess** [comment]
@Jan-Blasiak I've uploaded the rewritten version to this repository. It's the latest release, titled "Modern version".
